// `cn` class-merge helper — this is the exact utility generated by the
// 21st.dev Magic MCP component (it ships with every Magic component).
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
