// MagicStatCard
// -------------
// Built on the Card primitive + `cn` helper generated by the 21st.dev Magic
// MCP ("Stats cards with links" component), restyled for this project's
// cream + forest-green + gold theme.

import * as React from "react";
import { cn } from "../lib/cn";

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "rounded-xl2 border border-line bg-surface p-5 shadow-card transition-all duration-150",
        "hover:-translate-y-0.5 hover:shadow-cardhover",
        className
      )}
      {...props}
    />
  )
);
Card.displayName = "Card";

export interface StatCardProps {
  icon: React.ReactNode;
  label: string;
  value: React.ReactNode;
  sub?: string;
  deltaText?: string;
  sign?: number; // -1 down, 0 neutral, 1 up
  className?: string;
}

export default function MagicStatCard({
  icon,
  label,
  value,
  sub,
  deltaText,
  sign = 0,
  className,
}: StatCardProps) {
  const deltaColor = sign > 0 ? "text-pos" : sign < 0 ? "text-neg" : "text-ink-muted";
  const arrow = sign > 0 ? "▲" : sign < 0 ? "▼" : "";

  return (
    <Card className={cn("h-full", className)}>
      <div className="mb-3 flex h-11 w-11 items-center justify-center rounded-full bg-forest-tint text-forest-700 dark:text-forest-400">
        {icon}
      </div>
      <div className="text-[11.5px] font-bold uppercase tracking-wide text-ink-muted">{label}</div>
      <div className="num mt-1 text-[26px] font-extrabold leading-tight text-ink">{value}</div>
      {deltaText ? (
        <div className={cn("mt-1.5 flex items-center gap-1 text-xs font-semibold", deltaColor)}>
          {arrow && <span>{arrow}</span>}
          {deltaText}
        </div>
      ) : sub ? (
        <div className="mt-1.5 text-xs font-medium text-ink-muted">{sub}</div>
      ) : null}
    </Card>
  );
}
